### ISSUE TITLE
yaml.constructor (4.alpha)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#143] opened 2020-12-21 14:37 UTC
## Bug description
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/new:box.box.Box'

<details><summary>Full log output</summary>

```
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble4/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 123, in tool
    PyFunceble.facility.ConfigLoader.start()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 341, in start
    config = self.get_config_file_content()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 291, in get_config_file_content
    config = self.dict_helper.from_yaml_file(self.path_to_config)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/helpers/dict.py", line 291, in from_yaml_file
    data = yaml_load(file_stream)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/new:box.box.Box'
  in "$HOME/miniconda/envs/pyfunceble4/.PyFunceble.yaml", line 1, column 1
```

</details>

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

1. ./pyfunceble4.sh /var/storage01/repos/github/mypdns/porn-records/submit_here/adult.mypdns.cloud/snuff.list
2. Enter output directory for test results: /tmp/pyfunceble4/1520
Which version of PyFunceble would you like to use?: pyfunceble4: pyfunceble4
Enter any custom test string: -dbr 0 -ex --dns 127.0.0.1 192.168.1.53:5302 -w 6 --database-type mariadb --no-files                                              
Would you like to use your default pyfunceble enviroment
  /home/joakim/miniconda/envs/pyfunceble4?: [Y/n] Y
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Versions

**OS:** Ubuntu 20 + conda
**Python Version:**  3.9.1
**PyFunceble Version:** 4.0.0a8

## Additional context
Switched the DB on same target hosts. It should have initiated a conversion of the 3.3.7 DB tables to 4.0.0a8 table layout

**Comment by spirillen** [comment] 2020-12-21 14:47
Appendix

Same happens on fresh pyfunceble-alpha DB

`rm .pyfunceble-env .PyFunceble.yaml` Fixed the issue...

**Comment by spirillen** [comment] 2020-12-21 14:58
Appendix 2.

The issue arises every time I make any changes to `.pyfunceble-env` currently only option is to actually delete `.PyFunceble.yaml`

**Comment by funilrys** [comment] 2020-12-21 15:09
Busy with the documentation right now. Will look into that later today. I could not reproduce this 😢

**Comment by spirillen** [comment] 2020-12-21 15:27
> Busy with the documentation right now. Will look into that later today. I could not reproduce this cry

keybase://chat/spirillen,funilrys/1975

**Comment by spirillen** [comment] 2020-12-22 10:33
Just tested with 4.0.0a13 and the issue has raised in severity :unamused: 

This time I haven't made any changes to any files, the only change I've done from previous test is hanging the test file....

Test string `-dbr 0 -ex --dns 127.0.0.1 -w 6 --database-type mariadb --syntax --no-files`

```python
pyfunceble 4.0.0a13.dev (Blue Duckling)
Traceback (most recent call last):
  File "/$HOME/miniconda/envs/pyfunceble4/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 123, in tool
    PyFunceble.facility.ConfigLoader.start()
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 341, in start
    config = self.get_config_file_content()
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 291, in get_config_file_content
    config = self.dict_helper.from_yaml_file(self.path_to_config)
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/helpers/dict.py", line 291, in from_yaml_file
    data = yaml_load(file_stream)
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/new:box.box.Box'
  in "/$HOME/miniconda/envs/pyfunceble4/.PyFunceble.yaml", line 1, column 1
```

**Comment by funilrys** [comment] 2020-12-22 23:02
Closing. Feel free to test and reopen if not fixed.

**Closed by funilrys** 2020-12-22 23:02 UTC
Labels: bug

**Comment by spirillen** [comment] 2020-12-23 02:14
Confirmed
