### ISSUE TITLE
PYFUNCEBLE_AUTO_CONFIGURATION (4.0.0a27.dev)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#151] opened 2020-12-25 10:57 UTC
## Bug description
`PYFUNCEBLE_AUTO_CONFIGURATION=yes` Is not in effect :unamused: 

<https://github.com/PyFunceble-Templates/pyfunceble-miniconda/blob/a5281d1c0ca15d5a2933efb62ea05e29f4b00edf/pyfunceble4.sh#L126>

```python
# All requested packages already installed.

The 'cli_testing.display_mode.status' key is missing from your configuration file.
Are we authorized to merge it from upstream ? [y/n]
```

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

1. Run https://github.com/funilrys/PyFunceble/issues/147#issuecomment-750177740 without the `--database-type mariadb` argument

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/103133049-81bc8d80-46a8-11eb-8eb8-7964d9c1bf73.png)

## Versions

**OS:** Ubuntu 20.04 with Conda
**Python Version:** 3.9.1
**PyFunceble Version:** 4.0.0a27.dev

## Additional context
Related to #115 & #43

**Comment by spirillen** [comment] 2020-12-25 11:25
Appendix 1:

Same happens with pi4 in venv <https://github.com/PyFunceble-Templates/pyfunceble-miniconda/blob/a5281d1c0ca15d5a2933efb62ea05e29f4b00edf/pyfunceble4-arm7.sh>

**Comment by spirillen** [comment] 2020-12-25 11:51
Appendix 2

Same goes for `PYFUNCEBLE_OUTPUT_LOCATION`

**Comment by funilrys** [comment] 2020-12-26 00:23
# `PYFUNCEBLE_AUTO_CONFIGURATION`

I can't reproduce for `PYFUNCEBLE_AUTO_CONTINUE`.

## Manual:

```
$ PyFunceble -d github.com
The 'cli_testing.whois_db' key is missing from your configuration file.
Are we authorized to merge it from upstream ? [y/n] y

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝



Subject                                                                                              Status      Source    
---------------------------------------------------------------------------------------------------- ----------- ----------
github.com                                                                                           ACTIVE      WHOIS     

Thanks for using PyFunceble!
Have a feedback, an issue or an improvement idea? Let us know on GitHub!
```

##  With environment variable (PREFIXED)

```
$ PyFunceble -d github.com
The 'cli_testing.whois_db' key is missing from your configuration file.
Are we authorized to merge it from upstream ? [y/n] n
Could not find the 'cli_testing.whois_db' in your configuration.
Please fix your configuration file manually or fill a new issue if you don't understand this error.

$ PyFunceble -d github.com
The 'cli_testing.whois_db' key is missing from your configuration file.
Are we authorized to merge it from upstream ? [y/n] n
Could not find the 'cli_testing.whois_db' in your configuration.
Please fix your configuration file manually or fill a new issue if you don't understand this error.

$ PYFUNCEBLE_AUTO_CONFIGURATION=yes PyFunceble -d github.com

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝



Subject                                                                                              Status      Source    
---------------------------------------------------------------------------------------------------- ----------- ----------
github.com                                                                                           ACTIVE      WHOIS     

Thanks for using PyFunceble!
Have a feedback, an issue or an improvement idea? Let us know on GitHub!
```

##  With environment variable (EXPORTED)

```
$ PyFunceble -d github.com
The 'cli_testing.whois_db' key is missing from your configuration file.
Are we authorized to merge it from upstream ? [y/n] n
Could not find the 'cli_testing.whois_db' in your configuration.
Please fix your configuration file manually or fill a new issue if you don't understand this error.

$ PyFunceble -d github.com
The 'cli_testing.whois_db' key is missing from your configuration file.
Are we authorized to merge it from upstream ? [y/n] n
Could not find the 'cli_testing.whois_db' in your configuration.
Please fix your configuration file manually or fill a new issue if you don't understand this error.

$ export PYFUNCEBLE_AUTO_CONFIGURATION=yes

$ PyFunceble -d github.com

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝



Subject                                                                                              Status      Source    
---------------------------------------------------------------------------------------------------- ----------- ----------
github.com                                                                                           ACTIVE      WHOIS     

Thanks for using PyFunceble!
```

**Comment by funilrys** [comment] 2020-12-26 00:28
# `PYFUNCEBLE_OUTPUT_LOCATION`

I can't reproduce for `PYFUNCEBLE_OUTPUT_LOCATION` (too).

## Reproduction

```
$ export PYFUNCEBLE_OUTPUT_LOCATION=/tmp/hello_spirillen

$ ls -al /tmp | grep spiri

$ PyFunceble -uf test_this_url 

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝



Subject                                                                                              Status      Source    
---------------------------------------------------------------------------------------------------- ----------- ----------
http://phish.co.za                                                                                   ACTIVE      HTTP CODE 
http://aur.ilrysfun.com                                                                              ACTIVE      HTTP CODE 


Status      Percentage   Amount      
----------- ------------ ------------
ACTIVE      100%         2           
INACTIVE    0%           0           
INVALID     0%           0           

Thanks for using PyFunceble!
Share your experience on Twitter with #PyFunceble or @PyFunceble!

$ tree /tmp/hello_spirillen/
/tmp/hello_spirillen/
└── output
    └── test_this_url
        ├── Analytic
        │   ├── ACTIVE
        │   ├── POTENTIALLY_ACTIVE
        │   ├── POTENTIALLY_INACTIVE
        │   │   └── potentially_up
        │   └── SUSPICIOUS
        ├── counter.json
        ├── domains
        │   ├── ACTIVE
        │   │   └── list
        │   ├── INACTIVE
        │   ├── INVALID
        │   ├── MALICIOUS
        │   ├── SANE
        │   └── VALID
        ├── hosts
        │   ├── ACTIVE
        │   ├── INACTIVE
        │   ├── INVALID
        │   ├── MALICIOUS
        │   ├── SANE
        │   └── VALID
        ├── logs
        │   ├── inactive_not_retested
        │   └── percentage
        │       └── percentage.txt
        └── splitted
            └── ACTIVE

24 directories, 6 files
```

**Comment by funilrys** [comment] 2020-12-26 00:31
Closing, as I may need more context. Could not reproduce the behavior on 2 different machines.

Feel free to reopen with more context.

**Comment by spirillen** [comment] 2020-12-26 01:27
The keyword is the `export` :smiley: 

I found that issue later, but what buggers me, is it as such, shouldn't be necessary to use export statement to assign a variable to same bash shell with no sub-processes (this case) as the are going 1,2,3 etc. This might rather relate to bash than PyFunceble.

**Comment by funilrys** [comment] 2020-12-26 01:48
Well, without `export` it should only stay on your user level. Meaning that if I'm not wrong, it is never caught by subsequential scripts.  

I use `export` for so much time, that it became an automatism. 😆

**Comment by spirillen** [comment] 2020-12-26 10:29
Yep, but it can also become problematic that you export to global level.

Let's take a though case, and yet one I have experienced my self.

at 10:00 I start a job with EXPORT (Global change of GLABAL variables, the script is running and hours are parsing by.

at 17:00 (First script still running in shell1) I then have to test something else in shell 2. How I have forgotten I did an EXPORT in shell 1 and I get a result I didn't expect, cos I forgot to reset GLOB variables like `PYFUNCEBLE_OUTPUT_LOCATION` which is set to a new fixed value over default  `./output/`.

So it isn't entirely without "challenges" that it should be necessary to et global val (export).

However, there is a more practically solution to this. make them as arg

`--PYFUNCEBLE_OUTPUT_LOCATION some-path --PYFUNCEBLE_AUTO_CONFIGURATION (yes|true)|(no|false)`

:question: Could this work for you?

**Comment by spirillen** [comment] 2020-12-26 14:42
```bash
./pyfunceble4.sh test.list 
        I'm your hungry cheese missing a piece...
        Are you ready to go hunting the red pills
        so we can hunt down evil ghosts

        Are you ready to start?

        loading kacman...
Enter output directory for test results: /tmp/pyfunceble4/1538
Which version of PyFunceble would you like to use?: pyfunceble4: pyfunceble4
Enter any custom test string: --share-logs -dbr 6 -ex --dns 192.168.1.104:53 -w 6 -a --database-type mariadb --wildcard
Would you like to use your default pyfunceble enviroment
  /home/joakim/miniconda/envs/pyfunceble4?: [Y/n] Y
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/joakim/miniconda

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    tqdm-4.55.0                |     pyhd8ed1ab_0          73 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          73 KB

The following packages will be UPDATED:

  tqdm                                  4.54.1-pyhd8ed1ab_1 --> 4.55.0-pyhd8ed1ab_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
The 'cli_testing.display_mode.status' key is missing from your configuration file.
Are we authorized to merge it from upstream ? [y/n] y
pyfunceble 4.0.0a30.dev (Blue Duckling)
uhb-whitelist 3.25.0
pyfunceble 4.0.0a30.dev (Blue Duckling)
```

**Comment by spirillen** [comment] 2020-12-27 13:53
Test failed...

```bash
./pyfunceble4.sh test.list 
        I'm your hungry cheese missing a piece...
        Are you ready to go hunting the red pills
        so we can hunt down evil ghosts

        Are you ready to start?

        loading kacman...
Enter output directory for test results: /tmp/pyfunceble4/1450
Which version of PyFunceble would you like to use?: pyfunceble4: pyfunceble4
Enter any custom test string: --share-logs -dbr 6 -ex --dns 192.168.1.104:53 -w 2 --database-type mariadb --no-files --wildcard
Would you like to use your default pyfunceble enviroment
  /$HOME/miniconda/envs/pyfunceble4?: [Y/n] Y
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

The 'cli_testing.display_mode.status' key is missing from your configuration file.
Are we authorized to merge it from upstream ? [y/n] y
pyfunceble 4.0.0a34.dev (Blue Duckling)
```

**Comment by spirillen** [comment] 2020-12-27 18:54
Got this on a fresh user profile

```python
Python 3.9.1 (default, Dec 11 2020, 14:32:07) 
[GCC 7.3.0]
pip 20.3.3 from /home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/pip (python 3.9)
Traceback (most recent call last):
  File "/home/spirillen/miniconda/envs/pyfunceble4/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 961, in tool
    PyFunceble.facility.ConfigLoader.start()
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 348, in start
    config = self.get_config_file_content()
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 306, in get_config_file_content
    config = ConfigComparison(
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/compare.py", line 302, in get_merged
    raise RuntimeError(f"<value> {value!r} not found.")
RuntimeError: <value> 'cli_decoding.adblock' not found.
```

**Comment by spirillen** [comment] 2020-12-27 20:55
Sill minor troubles 4.0.0a35.dev, but should be fixable by ensuring cleaning all v3 files from `~/.config/PyFunceble` | `./.env`

```python
conda activate pyfunceble4
spirillen@e350c:/var/storage01/repos/github/PyFunceble-Templates/pyfunceble-miniconda$ pip install --no-cache-dir --upgrade -q 'git+https://github.com/funilrys/PyFunceble@4.0.0-dev#egg=PyFunceble-dev'
spirillen@e350c:/var/storage01/repos/github/PyFunceble-Templates/pyfunceble-miniconda$ pyfunceble --version
Traceback (most recent call last):
  File "/home/spirillen/miniconda/envs/pyfunceble4/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 961, in tool
    PyFunceble.facility.ConfigLoader.start()
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 348, in start
    config = self.get_config_file_content()
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 306, in get_config_file_content
    config = ConfigComparison(
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/compare.py", line 302, in get_merged
    raise RuntimeError(f"<value> {value!r} not found.")
RuntimeError: <value> 'cli_decoding.adblock' not found.
```

After deleting all non v4 related files from `~/.config/PyFunceble` everything was fine

**Comment by funilrys** [comment] 2020-12-27 23:12
I can implement the `--ouput-location` but the autoconfiguration part is not that easy because that means removing the `Configured value: XXX` when using the`--help` argument.

**Comment by spirillen** [comment] 2020-12-28 13:31
I would like `--ouput-location` as it would make bash|command line scripting easier.

However, for the issue in question, I believe we should do was is the easy way, delete non v4 files then generate|download v4 related. :thinking:

**Comment by funilrys** [comment] 2020-12-28 20:04
`--output-location` is in there (previous commit referenced here) 😄

**Comment by funilrys** [comment] 2020-12-28 20:20
> Sill minor troubles 4.0.0a35.dev, but should be fixable by ensuring cleaning all v3 files from `~/.config/PyFunceble` | `./.env`
> 
> ```python
> conda activate pyfunceble4
> spirillen@e350c:/var/storage01/repos/github/PyFunceble-Templates/pyfunceble-miniconda$ pip install --no-cache-dir --upgrade -q 'git+https://github.com/funilrys/PyFunceble@4.0.0-dev#egg=PyFunceble-dev'
> spirillen@e350c:/var/storage01/repos/github/PyFunceble-Templates/pyfunceble-miniconda$ pyfunceble --version
> Traceback (most recent call last):
>   File "/home/spirillen/miniconda/envs/pyfunceble4/bin/pyfunceble", line 8, in <module>
>     sys.exit(tool())
>   File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 961, in tool
>     PyFunceble.facility.ConfigLoader.start()
>   File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 348, in start
>     config = self.get_config_file_content()
>   File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 306, in get_config_file_content
>     config = ConfigComparison(
>   File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/config/compare.py", line 302, in get_merged
>     raise RuntimeError(f"<value> {value!r} not found.")
> RuntimeError: <value> 'cli_decoding.adblock' not found.
> ```
> 
> After deleting all non v4 related files from `~/.config/PyFunceble` everything was fine

Patch on it's way.

**Closed** 2020-12-28 20:29 UTC
Labels: bug

**Comment by spirillen** [comment] 2020-12-30 01:17
TEST: OK :heavy_check_mark:
