### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#148] opened 2020-12-23 20:20 UTC
## Bug description
Use the following command and after a few seconds you will get the error...

```bash
Traceback (most recent call last):
  File "/root/.local/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/root/.local/lib/python3.9/site-packages/PyFunceble/cli/__init__.py", line 1222, in tool
    raise exception
  File "/root/.local/lib/python3.9/site-packages/PyFunceble/cli/__init__.py", line 1207, in tool
    Dispatcher(
  File "/root/.local/lib/python3.9/site-packages/PyFunceble/cli/dispatcher.py", line 131, in __init__
    self.dispatch_file_test(
  File "/root/.local/lib/python3.9/site-packages/PyFunceble/cli/dispatcher.py", line 174, in dispatch_file_test
    PyFunceble.core.Multiprocess(file_path, "domain").run_test()
  File "/root/.local/lib/python3.9/site-packages/PyFunceble/core/multiprocess.py", line 575, in run_test
    self.__run_multiprocess_test(shadow_file, manager, tracker=tracker)
  File "/root/.local/lib/python3.9/site-packages/PyFunceble/core/multiprocess.py", line 428, in __run_multiprocess_test
    self.__start_process(
  File "/root/.local/lib/python3.9/site-packages/PyFunceble/core/multiprocess.py", line 331, in __start_process
    process.start()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 65, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files

```

## Modifications under `.PyFunceble.yaml`

no

## Reproduction

`sudo /root/.local/bin/pyfunceble -m -p 4 --no-whois -a --syntax -f "/home/URLsToScan.txt"
`

## Versions

**OS:** Arch Linux 5.10.1-Custom2-2-ARCH
**Python Version:** 3.9.X
**PyFunceble Version:** 3.3.7

**Comment by spirillen** [comment] 2020-12-23 21:58
Damned, you too.

Duplicate of <https://github.com/funilrys/PyFunceble/issues/129>

**Comment by funilrys** [comment] 2020-12-23 22:02
PyFunceble version. 

@ZeroDot1, I will publish 4.0.0-dev  to the AUR as soon as we are out of beta. Until then please install it manually into a virtualenv. @spirillen or @mitchellkrogza may support your if I'm not around (that fast).

**Comment by funilrys** [comment] 2020-12-24 01:03
Closing.

**Closed by funilrys** 2020-12-24 01:03 UTC
