### ISSUE TITLE
Bug, some invalid (incorrect TLD) URLs were not detected.

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#204] opened 2021-01-20 18:18 UTC
Hi @funilrys A new bug, some invalid (incorrect TLD) URLs were not detected.

For examples see the following link: https://gitlab.com/ZeroDot1/CoinBlockerLists/-/commit/6a934f6ab4ba188c3f28c575c9c4d5304fc6c7f7

_Originally posted by @ZeroDot1 in https://github.com/funilrys/PyFunceble/issues/134#issuecomment-763836312_

These are valid TLD's

```
0.0.0.0 thepiratebay.be
0.0.0.0 thepiratebay.bl
0.0.0.0 thepiratebay.cr
0.0.0.0 thepiratebay.is
0.0.0.0 thepiratebay.ki
```

but I admit info**s** isn't :smiley:

**Comment by ZeroDot1** [comment] 2021-01-20 18:34
Here is a list of inavlid URLs/TLDs:

```go
2giga.do #tld
cookiescript.infos #tld
smartoffer.si #tld
support.2giga.li #tld
template-download.to #tld
us.cfcnet.to #tld
www.datasecu.do #tld
www.freecontent.bi #tld
www.freecontent.do #tld
www.freecontent.pa #tld
www.freecontent.re #tld
www.freecontent.sc #tld
www.freecontent.st #tld
www.freecontent.tr #tld
www.hostingcloud.ac #tld
www.hostingcloud.bi #tld
xmr.mining.be #tld
```

**Comment by spirillen** [comment] 2021-01-20 20:28
Super thanks for the follow up :+1:

**Comment by spirillen** [comment] 2021-01-20 20:40
`ac` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L11>
`be` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L122>
`bi` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L135>
`do` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L354>
`li` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L712>
`pa` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L914>
`re` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L993>
`sc` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L1061>
`si` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L1104>
`st` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L1140>
`to` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L1215>
`tr` is a valid TLD <https://github.com/mypdns/tld/blob/c9bb295c9d8e7e7cad374acabafb1d9c97ae541c/tld.list#L1227>


If you would like to challange my list, here is the link to the IANA source <http://data.iana.org/TLD/tlds-alpha-by-domain.txt>
`` is a valid TLD <>

**Comment by funilrys** [comment] 2021-01-20 21:02
Are we talking about the same thing?

```
$ pyfunceble --version
pyfunceble 4.0.0b14.dev (Blue Duckling)
$ pyfunceble -f issue-204 --syntax -s
thepiratebay.be VALID
thepiratebay.cr VALID
2giga.do VALID
cookiescript.infos INVALID
thepiratebay.bl VALID
smartoffer.si VALID
thepiratebay.is VALID
thepiratebay.ki VALID
template-download.to VALID
us.cfcnet.to VALID
support.2giga.li VALID
www.freecontent.bi VALID
www.freecontent.pa VALID
www.freecontent.do VALID
www.freecontent.sc VALID
www.freecontent.re VALID
www.freecontent.st VALID
www.hostingcloud.ac VALID
www.freecontent.tr VALID
www.hostingcloud.bi VALID
xmr.mining.be VALID
www.datasecu.do VALID


Status      Percentage   Amount      
----------- ------------ ------------
VALID       95%          21          
INVALID     25%          1           
```

**Comment by funilrys** [comment] 2021-01-20 21:03
Closing as I couldn't reproduce. Feel free to add more context and reopen.

**Closed** 2021-01-20 21:03 UTC

**Comment by funilrys** [comment] 2021-01-20 21:05
For the record, PyFunceble uses https://www.iana.org/domains/root/db.

**Comment by spirillen** [comment] 2021-01-21 01:21
/reopen

No @ZeroDot1 talking about 2 things
  1. A number of TLDøs he concidered wrong
  2. That there actually is errors in the handling of the TLD in his result `cookiescript.infos #tld`

There are no TLD .info**s**

**Comment by ZeroDot1** [comment] 2021-01-21 01:37
Everything is completely wrong. The point is that incomplete TLDs cannot be separated from complete ones.
e.g. freecontent.st (.ST) exists, but this is invalid for the domain (freecontent.stream), .stream is the correct TLD for the domain.

**Comment by ZeroDot1** [comment] 2021-01-21 01:50
Additional screenshot to show the whole thing better. 
![Bildschirmfoto vom 2021-01-21 02-48-52](https://user-images.githubusercontent.com/28985171/105268945-5d62ac80-5b93-11eb-8b61-56eec413dc1b.png)

**Comment by ZeroDot1** [comment] 2021-01-21 01:58
I recommend to include an extra step e.g. `--syntx --tldcheck` to be able to check the correctness of the TLD also separately from a quick syntax check.
Sort a fastmode and a detailmode.

**Comment by spirillen** [comment] 2021-01-21 11:01
> https://urlscan.io/api/v1/result/b59aa41e-00a1-48a2-8fb4-60ec33a08112/

<details><summary>Just a note for other, that urlscan.io is unsafe.... (track- spyware infected)</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +18 | `##[href^="https://twitter.com"]` |  | urlscan.io |  | dom | `https://urlscan.io/result/scan/` |
| +18 | ##.sc--twitter |  | urlscan.io |  | dom | `https://urlscan.io/result/scan/` |
| +18 | no-remote-fonts: * true | -- | urlscan.io | 1 | font | `https://urlscan.io/vendor/bootstrap/fonts/glyphicons-halflings-regular.ttf` |
| +18 | no-remote-fonts: * true | -- | urlscan.io | 1 | font | `https://urlscan.io/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff` |
| +18 | no-remote-fonts: * true | -- | urlscan.io | 1 | font | `https://urlscan.io/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff2` |
| +18 | \|\|googleapis.com^$important | -- | urlscan.io | 3 | css | `https://fonts.googleapis.com/css?family=Lato:400,700,400italic&display=swap` |
| +18 | no-remote-fonts: * true | -- | urlscan.io | 1 | inline-font | `https://urlscan.io/result/scan/` |
| +1 | `##[href^="https://twitter.com"]` |  | urlscan.io |  | dom | `https://urlscan.io/` |
| +1 | ##.sc--twitter |  | urlscan.io |  | dom | `https://urlscan.io/` |
| +0 | no-remote-fonts: * true | -- | urlscan.io | 1 | font | `https://urlscan.io/vendor/bootstrap/fonts/glyphicons-halflings-regular.ttf` |
| +0 | no-remote-fonts: * true | -- | urlscan.io | 1 | font | `https://urlscan.io/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff` |
| +0 | no-remote-fonts: * true | -- | urlscan.io | 1 | font | `https://urlscan.io/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff2` |
| +0 | \|\|googleapis.com^$important | -- | urlscan.io | 3 | css | `https://fonts.googleapis.com/css?family=Lato:400,700,400italic&display=swap` |
| +0 | \|\|google.com^*recaptcha/$important | -- | urlscan.io | 3 | script | `https://www.google.com/recaptcha/api.js` |
| +0 | no-remote-fonts: * true | -- | urlscan.io | 1 | inline-font | `https://urlscan.io/` |
</details>

For your suggestion about a TLD only check (`--syntax --tldcheck`) I'm open for the idea, but is there any bigger use case for it vs doing the full validation of the entire string?

To translate the error into short, you are saying PyFunceble is shopping off parts of the TLD's?

Now I do happens to hold a relative fresh test of your list, however I can find the records your are referring to.

```console
grep -riE '\.infos$' output/coinblocker.txt/domains/ coinblocker.txt
    EMPTY response

grep -riE 'freecontent\.bi' output/coinblocker.txt/domains/ coinblocker.txt | cut -d ':' -f 2 | sort -u
freecontent.bi
freecontent.bid
www.freecontent.bi
www.freecontent.bid
```

Have you checked your source file for these records as they would pass the filters as valid.

I'm asking because the full search of `freecontent.bi.*` only returned the 2 cases from above

<details><summary>Full search output of freecontent.bi</summary>

1.freecontent.bid
admin.freecontent.bid
administration.freecontent.bid
adserver.freecontent.bid
ads.freecontent.bid
alerts.freecontent.bid
alpha.freecontent.bid
apache.freecontent.bid
ap.freecontent.bid
app.freecontent.bid
beta.freecontent.bid
blog.freecontent.bid
cdn.freecontent.bid
corp.freecontent.bid
crs.freecontent.bid
dhcp.freecontent.bid
dns0.freecontent.bid
download.freecontent.bid
erp.freecontent.bid
exchange.freecontent.bid
fileserver.freecontent.bid
forum.freecontent.bid
freecontent.bi
freecontent.bid
git.freecontent.bid
host.freecontent.bid
ldap.freecontent.bid
mail.freecontent.bid
mailgate.freecontent.bid
manage.freecontent.bid
ns0.freecontent.bid
nwww.freecontent.bid
smtp.freecontent.bid
squid.freecontent.bid
stats.freecontent.bid
syslog.freecontent.bid
test.freecontent.bid
vm.freecontent.bid
vnc.freecontent.bid
web.freecontent.bid
whois.freecontent.bid
ww.freecontent.bid
www.freecontent.bi
www.freecontent.bid
wxw.freecontent.bid

</details>

And if the case should be, that PyFunceble should be cropping the TLD I would have expected it to have been done on all of them.

Is it possible you would share your raw sources with us for testing - reproduciblity?
