### ISSUE TITLE
ModuleNotFoundError: No module named 'box'

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#147] opened 2020-12-23 05:56 UTC
## Bug description
I wanted to do the final error check before updating the [CoinBlockerLists](https://zerodot1.gitlab.io/CoinBlockerListsWeb/).
In order to be able to publish the lists as planned on 24.12.2020.
But unfortunately there was only the following error:

```
pyfunceble -m -a --syntax -f "/home/user/URLsToScan.txt"
Traceback (most recent call last):
  File "/usr/bin/pyfunceble", line 33, in <module>
    sys.exit(load_entry_point('PyFunceble-dev==3.3.4', 'console_scripts', 'pyfunceble')())
  File "/usr/bin/pyfunceble", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/PyFunceble/__init__.py", line 61, in <module>
    from PyFunceble import config as cconfig
  File "/usr/lib/python3.9/site-packages/PyFunceble/config/__init__.py", line 53, in <module>
    from .loader import Loader
  File "/usr/lib/python3.9/site-packages/PyFunceble/config/loader.py", line 57, in <module>
    from box import Box
ModuleNotFoundError: No module named 'box'

```

All required packages have been installed, the same error also occurs with the non DEV version.

It is a bit frustrating that there are problems almost every time although I have not changed anything except installing the regular updates.
I hope such problems can be avoided in the future.
## Modifications under `.PyFunceble.yaml`

no

## Versions

**OS:** for example Arch Linux (5.10.1-custom1-1-ARCH)
**Python Version:** 3x
**PyFunceble Version:** 3.3.4-1

**Comment by spirillen** [comment] 2020-12-23 11:05
The reason could lie in the fact you have been tested with the same version :unamused: 

`PyFunceble-dev==3.3.4` is the esact same as `PyFunceble==3.3.4`

The latest 3.x dev version is `PyFunceble-dev==3.3.7` could you try to update the dev to this version and try again as the `box` error should have been fixed. (I had it too)

Could you also try the 4.x.alpha on your list??

In case you need a shortcut script I have one here: <https://github.com/PyFunceble-Templates/pyfunceble-miniconda> it will be using conda, but setup 3 environments, stable, dev and 4.x.alpha

**Comment by spirillen** [comment] 2020-12-23 11:27
Own note for testing in alpha, @ZeroDot1 please fill in if I forgot one basis list

```shell
pyfunceble -dbr 6 -ex --dns 192.168.1.104:53 -w $(nproc --ignore=2) -a --database-type mariadb \
  -f https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts \
  -f https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts_optional \
  -f https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt \
  -f https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_optional.txt \
  -f https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser.txt \
   --no-files
```

@funilrys Can you please this issue to the re-test project, if you decide to set it up?

**Comment by ZeroDot1** [comment] 2020-12-23 20:34
@spirillen The box error is fixed, but I found another one immediately.
See: https://github.com/funilrys/PyFunceble/issues/148

**Comment by spirillen** [comment] 2020-12-23 22:01
Yeah, and it's not going to be fixed, it's a duplicate of #129 

OT: Just to be curious, what is your `ulimit -n`?

I'm testing the https://github.com/funilrys/PyFunceble/issues/147#issuecomment-750177740 as we speech, so far it seems promising with the v4.x.alpha

**Comment by spirillen** [comment] 2020-12-23 22:06
Self note, this test will also touch #115

**Comment by funilrys** [comment] 2020-12-23 22:14
@ZeroDot1 AS a temporary solution: `pip install python-box` (from virtualenv presumly) OR `aur-helper -S python-box`  (system-wide)

**Comment by funilrys** [comment] 2020-12-24 01:03
Closing because I'm more focused on 4.0 and a temporary solution was presented (previous comment).

**Comment by spirillen** [comment] 2020-12-25 15:15
Hey @ZeroDot1 

To do a followup, have you been able to run a full successful test your self, and if Which version did you use?

**Comment by spirillen** [comment] 2020-12-30 03:14
just to be a killswitch.... haven't with v4 too

```python
pyfunceble -v
Traceback (most recent call last):
  File "/usr/local/bin/pyfunceble", line 5, in <module>
    from PyFunceble.cli.entry_points.pyfunceble.cli import tool
  File "/usr/local/lib/python3.9/dist-packages/PyFunceble/__init__.py", line 56, in <module>
    from PyFunceble.checker.availability.domain import DomainAvailabilityChecker
  File "/usr/local/lib/python3.9/dist-packages/PyFunceble/checker/availability/domain.py", line 58, in <module>
    from PyFunceble.checker.availability.extra_rules import ExtraRulesHandler
  File "/usr/local/lib/python3.9/dist-packages/PyFunceble/checker/availability/extra_rules.py", line 57, in <module>
    from box.box import Box
ModuleNotFoundError: No module named 'box.box'; 'box' is not a package
```

**Closed** 2020-12-31 14:19 UTC
Labels: bug

**Comment by spirillen** [comment] 2021-01-06 23:16
Solved for me in two cases :heavy_check_mark:

**Comment by ZeroDot1** [comment] 2021-01-08 01:45
Hi @funilrys I just installed the latest DEV version from the AUR, unfortunately the error still occurs.
All required packages were completely uninstalled and then reinstalled.

`yay -S domain2idna python-alembic python-box python-colorama python-cryptography python-distribute python-dnspython python-dotenv python-inflection python-msgpack python-pyaml python-pymysql python-requests python-ruamel-yaml python-setuptools python-sqlalchemy python-toml python3
`

```py
Traceback (most recent call last):
  File "/usr/bin/pyfunceble", line 33, in <module>
    sys.exit(load_entry_point('PyFunceble-dev==4.0.0b1', 'console_scripts', 'pyfunceble')())
  File "/usr/bin/pyfunceble", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/PyFunceble/__init__.py", line 55, in <module>
    import PyFunceble.storage
  File "/usr/lib/python3.9/site-packages/PyFunceble/storage.py", line 58, in <module>
    from box import Box
ModuleNotFoundError: No module named 'box'

```

**Comment by ZeroDot1** [comment] 2021-01-08 01:53
```py
pyfunceble -v
Traceback (most recent call last):
  File "/usr/bin/pyfunceble", line 33, in <module>
    sys.exit(load_entry_point('PyFunceble-dev==4.0.0b1', 'console_scripts', 'pyfunceble')())
  File "/usr/bin/pyfunceble", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/PyFunceble/__init__.py", line 55, in <module>
    import PyFunceble.storage
  File "/usr/lib/python3.9/site-packages/PyFunceble/storage.py", line 58, in <module>
    from box import Box
ModuleNotFoundError: No module named 'box'

```

**Comment by spirillen** [comment] 2021-01-08 19:33
The box module sure makes some noise...

What does this command gives you?

```shell
pip3 list | grep 'box'
python-box                    5.2.0
```

**Comment by funilrys** [comment] 2021-01-08 19:36
I updated the `python-box` and `domain2idna` which I maintain in the AUR. 

Unfortunately, the following package is not matching the PyPi version.

community/python-dnspython 1:1.16.0-3 [installiert] 
    A DNS toolkit for Python  

It should be >=2.0.0.

I will have to write to the mailing list to ask for the status of that package 😞.

**Comment by funilrys** [comment] 2021-01-08 19:37
* Sorry for the waiting time, had a very long day.

**Comment by funilrys** [comment] 2021-01-08 21:41
This won't be easy because using dnspython 1.6 means no DOT or DOH. 

It won't be updated until some other issues are fixed as per https://bugs.archlinux.org/task/68546. 

Is `python-dnspython-git` (AUR) working on your machine?

**Comment by ZeroDot1** [comment] 2021-01-08 22:03
OK, I have now installed the updates, now new errors occur.

python-box  5.2.0-0 & domain2idna 1.12.0-2

```py
Traceback (most recent call last):
  File "/usr/bin/pyfunceble", line 33, in <module>
    sys.exit(load_entry_point('PyFunceble-dev==4.0.0b1', 'console_scripts', 'pyfunceble')())
  File "/usr/bin/pyfunceble", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/PyFunceble/__init__.py", line 56, in <module>
    from PyFunceble.checker.availability.domain import DomainAvailabilityChecker
  File "/usr/lib/python3.9/site-packages/PyFunceble/checker/availability/domain.py", line 55, in <module>
    import PyFunceble.factory
  File "/usr/lib/python3.9/site-packages/PyFunceble/factory.py", line 53, in <module>
    from PyFunceble.query.requests.requester import Requester as requester
  File "/usr/lib/python3.9/site-packages/PyFunceble/query/requests/requester.py", line 64, in <module>
    from PyFunceble.query.requests.adapter.http import RequestHTTPAdapter
  File "/usr/lib/python3.9/site-packages/PyFunceble/query/requests/adapter/http.py", line 59, in <module>
    from PyFunceble.query.requests.adapter.base import RequestAdapterBase
  File "/usr/lib/python3.9/site-packages/PyFunceble/query/requests/adapter/base.py", line 57, in <module>
    from PyFunceble.query.dns.query_tool import DNSQueryTool
  File "/usr/lib/python3.9/site-packages/PyFunceble/query/dns/query_tool.py", line 75, in <module>
    class DNSQueryTool:
  File "/usr/lib/python3.9/site-packages/PyFunceble/query/dns/query_tool.py", line 89, in DNSQueryTool
    x.value: x.name for x in dns.rdatatype.RdataType
AttributeError: module 'dns.rdatatype' has no attribute 'RdataType'

```

python-dnspython  1:1.16.0-3 -> python-dnspython-git v2.1.0.r2.9d435c1-1

```py
usage: pyfunceble [-d DOMAINS [DOMAINS ...]] [-u URLS [URLS ...]] [-f FILES [FILES ...]] [-uf URL_FILES [URL_FILES ...]]
                  [--adblock] [--complements] [--filter CLI_TESTING__FILE_FILTER] [--mining] [--rpz] [--wildcard] [-c]
                  [--cooldown-time CLI_TESTING__COOLDOWN_TIME] [--local] [--dns-lookup] [--http] [--netinfo-lookup]
                  [--special-lookup] [--whois-lookup] [--reputation-lookup] [--reputation] [--syntax] [-t LOOKUP__TIMEOUT]
                  [-ua USER_AGENT__CUSTOM] [-vsc] [--dns DNS__SERVER [DNS__SERVER ...]] [--dns-protocol {UDP,TCP,HTTPS,TLS}]
                  [--inactive-db] [--database-type {csv,mariadb,mysql}] [-dbr CLI_TESTING__DAYS_BETWEEN__DB_RETEST]
                  [-wdb CLI_TESTING__WHOIS_DB] [-a] [-ex] [--colour]
                  [--display-status {all,ACTIVE,INACTIVE,VALID,INVALID,MALICIOUS,SANE} [{all,ACTIVE,INACTIVE,VALID,INVALID,MALICIOUS,SANE} ...]]
                  [--hierarchical] [-h] [-ip CLI_TESTING__HOSTS_IP] [--no-files] [--output-location OUTPUT_LOCATION]
                  [--unified-results] [--percentage] [--plain] [--dots] [-q] [-s] [-w CLI_TESTING__MAX_WORKERS]
                  [--ci-max-minutes CLI_TESTING__CI__MAX_EXEC_MINUTES] [--ci] [--ci-branch CLI_TESTING__CI__BRANCH]
                  [--ci-distribution-branch CLI_TESTING__CI__DISTRIBUTION_BRANCH] [--cmd CLI_TESTING__CI__COMMAND]
                  [--cmd-before-end CLI_TESTING__CI__END_COMMAND] [--ci-commit-message CLI_TESTING__CI__COMMIT_MESSAGE]
                  [--ci-end-commit-message CLI_TESTING__CI__END_COMMIT_MESSAGE] [--help] [-v]
pyfunceble: error: unrecognized arguments: -m -p 4 --no-whois

```

**Comment by ZeroDot1** [comment] 2021-01-08 22:05
> *Sorry for the waiting time, had a very long day.

No problem, take your time. Rome was not built in a day.

**Comment by funilrys** [comment] 2021-01-08 22:24
@spirillen, is working on the docs right now. Until his work is merged here you can see what was deprecated at https://github.com/spirillen/PyFunceble/blob/4.x-patch/docs/usage/deprecated-variables.rst

**Comment by funilrys** [comment] 2021-01-08 22:28
In your case @ZeroDot1, it will be `pyfunceble -w 4 -a --syntax -f All.txt`

Note: there is actually no WHOIS lookup in place if you use the `--syntax` argument. But the `--no-whois` has been replaced with `--whois-lookup` (a switch of the default value of the configuration.

**Comment by ZeroDot1** [comment] 2021-01-09 11:23
OK, I'll take a look at it as soon as I can.
