### ISSUE TITLE
Mixing inout output lines

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#225] opened 2021-02-27 17:17 UTC
## Bug description
Easiest to show

Input file
![image](https://user-images.githubusercontent.com/44526987/109394468-6d567480-7927-11eb-8955-4ba50ec3f05a.png)

Output file
![image](https://user-images.githubusercontent.com/44526987/109394474-7cd5bd80-7927-11eb-8432-f98a83bc6aef.png)

## Modifications under `.PyFunceble.yaml`
<details><summary>pyfunceble.yaml</summary>

cli_decoding:
    adblock: false
    adblock_aggressive: false
    rpz: false
    wildcard: false
cli_testing:
    autocontinue: true
    ci:
        active: false
        branch: master
        command: null
        commit_message: My Privacy DNS - AutoSave
        distribution_branch: master
        end_command: null
        end_commit_message: My Privacy DNS - Results
        max_exec_minutes: 15
    complements: false
    cooldown_time: 0.0
    days_between:
        db_clean: 180
        db_retest: 1
    db_type: csv
    display_mode:
        all: false
        colour: true
        dots: false
        execution_time: false
        less: true
        percentage: true
        quiet: false
        simple: false
        status: all
    file_filter: null
    file_generation:
        analytic: true
        hosts: false
        no_file: false
        plain: true
        unified_results: false
    hosts_ip: 0.0.0.0
    inactive_db: true
    local_network: false
    max_workers: null
    mining: false
    preload_file: false
    sorting_mode:
        hierarchical: true
        standard: true
    testing_mode:
        availability: true
        reputation: false
        syntax: false
    whois_db: true
debug:
    active: false
    level: info
dns:
    follow_server_order: true
    trust_server: false
    protocol: UDP
    server:
        - 185.109.89.254
        - 130.225.244.166
        - 130.226.161.34
        - 185.38.24.52
        - 198.180.150.12
        - 94.126.178.9
        - 91.239.100.100
        - 89.233.43.71
        - 95.216.209.53
        - 116.203.32.67
        - 185.121.177.177
        - 169.239.202.202
        - 161.97.219.84
        - 104.168.144.17
        - 163.172.168.171
        - 94.103.153.176
        - 207.192.71.13
        - 178.63.116.152
        - 138.68.128.160
        - 188.226.146.136
        - 45.55.97.204
        - 79.124.7.81
http_codes:
    list:
        potentially_down:
            - 400
            - 402
            - 404
            - 409
            - 410
            - 412
            - 414
            - 415
            - 416
            - 451
        potentially_up:
            - 300
            - 301
            - 302
            - 303
            - 304
            - 305
            - 307
            - 308
            - 403
            - 405
            - 406
            - 407
            - 408
            - 411
            - 413
            - 417
            - 418
            - 421
            - 422
            - 423
            - 424
            - 426
            - 428
            - 431
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
            - 506
            - 507
            - 508
            - 510
            - 511
        up:
            - 100
            - 101
            - 102
            - 200
            - 201
            - 202
            - 203
            - 204
            - 205
            - 206
            - 207
            - 208
            - 226
            - 429
    self_managed: false
links:
    api_date_format: https://pyfunceble.funilrys.com/api/date-format
    api_no_referer: https://pyfunceble.funilrys.com/api/no-referer
    api_no_referrer: https://pyfunceble.funilrys.com/api/no-referrer
lookup:
    dns: true
    http_status_code: true
    netinfo: true
    reputation: false
    special: true
    timeout: 1
    whois: true
share_logs: false
user_agent:
    browser: firefox
    custom: null
    platform: linux
verify_ssl_certificate: false

</details>

## Reproduction

1. pyfunceble -f live.txt --database-type mariadb --follow-server-order --trust-dns-server
2. See error

## Expected behavior
Let's see :thinking: 

## Screenshots
:arrow_up_small: 

## Versions

**OS:** Ubuntu 20.04.1 :heavy_minus_sign: Conda
**Python Version:**  3.9
**PyFunceble Version:** 4.0.0b27.dev

## Additional context
Test file can be found here: <https://www.mypdns.org/P42>

**Comment by funilrys** [comment] 2021-02-28 08:30
😞 I tested 60 times with the same configuration and the file you provided and I can't reproduce this behavior 😢

**Comment by spirillen** [comment] 2021-02-28 10:48
> :disappointed: I tested 60 times with the same configuration and the file you provided and I can't reproduce this behavior :cry:

I thing that I came to think of is.... could the original vs the copied you tested against, actually hold some unwanted endings = mixed ending :thinking: as I have copied from various sources witch theoretically could be a mix of LF\CRLF\and even a tab :thinking:  The though came as I recalled, when copied one of the lines into it's issue, it had a unwanted line ending???, let me retest the file, and IF the same happens (ad I have cleaned out some dead/FP's and added comment to it), I'll sent it to you over keybase.

**Comment by spirillen** [comment] 2021-02-28 11:33
Sent....

**Comment by funilrys** [comment] 2021-02-28 21:40
Is this fixed now @spirillen ?

**Comment by spirillen** [comment] 2021-02-28 21:42
> Is this fixed now @spirillen ?

Let me get back when I've tested on https://www.mypdns.org/project/view/29/

**Closed** 2021-03-01 19:04 UTC
Labels: bug
