### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jawz101** [funilrys/PyFunceble#18] opened 2019-01-05 02:26 UTC
Installed latest stable and get this msg:

```
$ PyFunceble --version
PyFunceble 1.3.0. (Blue Bontebok: Dragonfly)
user@hp2570p:~/repos/PyFunceble-lists/blackjack$ PyFunceble -uf https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt

Traceback (most recent call last):
  File "/home/user/.local/bin/PyFunceble", line 11, in <module>
    sys.exit(_command_line())
  File "/home/user/.local/lib/python3.6/site-packages/PyFunceble/__init__.py", line 1120, in _command_line
    link_to_test=ARGS.link,
  File "/home/user/.local/lib/python3.6/site-packages/PyFunceble/core.py", line 129, in __init__
    self._entry_management()
  File "/home/user/.local/lib/python3.6/site-packages/PyFunceble/core.py", line 301, in _entry_management
    self.file_url()
  File "/home/user/.local/lib/python3.6/site-packages/PyFunceble/core.py", line 1064, in file_url
    PyFunceble.repeat(list_to_test[-1]),
IndexError: list index out of range
```

**Comment by funilrys** [comment] 2019-01-05 12:03
Hi @jawz101,
I can reproduce! 

It's because you're running 
```
$ PyFunceble -uf https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt
```

Instead of one of the following:

```
$ PyFunceble -f https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt
$ PyFunceble --link https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Hosts.txt
```

Indeed, if you ran with `-uf` the system test for 1 URL per line and not 1 domain/IP per line. That cause all domain to be marked as `INVALID` and stored in the local database `inactive_db.json`.
To explain simply, once they are in the database they are removed from the list to test because everything which is in the database has to be retested after x days (`days_between_db_retest` index of `.PyFunceble.yaml`).

I'll fix that behavior asap !

Thanks for reporting this.

Cheers,
Nissar

**Comment by funilrys** [comment] 2019-01-05 12:33
Fix introduced with https://github.com/funilrys/PyFunceble/commit/adcfa1fdcec41813654db87c99e56a7c14dca991.

It is now in the `dev` version.

**Please DO NOT close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/PyFunceble/commit/adcfa1fdcec41813654db87c99e56a7c14dca991 will be merged to master.**

**Closed** 2019-01-05 19:51 UTC
Labels: bug, enhancement
