### ISSUE TITLE
BUG: log file not created...

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#353] opened 2024-01-24 18:37 UTC
## Description
<details><summary>Debug log 1</summary>
<p>

```python
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.11/logging/handlers.py", line 74, in emit
self.doRollover()
File "/usr/lib/python3.11/logging/handlers.py", line 175, in doRollover
os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/home/$USER/Projects/pyfunceble/output/__pyfunceble_loggging__/debug.log.3' -> '/home/$USER/Projects/pyfunceble/output/__pyfunceble_loggging__/debug.log.4'
Call stack:
File "/home/$USER/.local/bin/pyfunceble", line 8, in <module>
sys.exit(tool())
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 1357, in tool
SystemLauncher(args).start()
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/system/base.py", line 90, in wrapper
return func(self, *args, **kwargs)  # pylint: disable=not-callable
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/system/launcher.py", line 1048, in start
self.fill_to_test_queue_from_protocol()
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/system/launcher.py", line 650, in fill_to_test_queue_from_protocol
handle_file(protocol)
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/system/launcher.py", line 593, in handle_file
self.tester_process_manager.add_to_input_queue(
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/processes/base.py", line 198, in wrapper
return func(self, *args, **kwargs)  # pylint: disable=not-callable
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/processes/base.py", line 406, in add_to_input_queue
PyFunceble.facility.Logger.debug("Added to the (main) queue: %r", data)
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/logger.py", line 378, in wrapper
return logger(*args, **kwargs, extra=self.get_origin())
Message: 'Added to the (main) queue: %r'
Arguments: {'type': 'file', 'subject_type': 'domain', 'destination': 'free_email_provider_domains.txt', 'source': 'free_email_provider_domains.txt', 'subject': 'veneersofficial.ru', 'checker_type': 'AVAILABILITY', 'session_id': '3087aa47600fcaf268103a4d', 'output_dir': '/home/$USER/Projects/pyfunceble/output/free_email_provider_domains.txt', 'idna_subject': 'veneersofficial.ru'}
```

</p>
</details>

<details><summary>Debug log 2</summary>
<p>

```python
Process pyfunceble_producer_worker_1:
Traceback (most recent call last):
File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/processes/workers/base.py", line 395, in run
raise exception
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/processes/workers/base.py", line 373, in run
result = self.target(consumed)
^^^^^^^^^^^^^^^^^^^^^
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/cli/processes/workers/producer.py", line 406, in target
self.collection_query_tool.push(test_result)
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/query/collection.py", line 393, in wrapper
return func(self, *args, **kwargs)  # pylint: disable=not-callable
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/query/collection.py", line 511, in push
self.__push_whois(checker_status)
File "/home/$USER/.local/lib/python3.11/site-packages/PyFunceble/query/collection.py", line 626, in __push_whois
raise TypeError(f"<data> should be {dict}, {type(data)} given.")
TypeError: <data> should be <class 'dict'>, <class 'PyFunceble.checker.availability.status.AvailabilityCheckerStatus'> given.
```

</p>
</details>  

## Configuration

Fully related to #352

**Comment by funilrys** [comment] 2024-03-26 15:49
May I ask how you activated the DEBUG mode ?  I can't reproduce ... Even with a forced exception at the same location.

**Comment by spirillen** [comment] 2024-03-30 02:12
I have it enabled in the `/home/$USER/.config/PyFunceble/.PyFunceble.overwrite.yaml`

```yaml
debug:
  active: true
  level: critical
```

**Comment by funilrys** [comment] 2024-12-27 11:38
Logging works as expected.

With the following settings:

```yml
debug:
  active: true
  level: critical
```

Nothing is written, when nothing critical is logged. 

With the following settings:

```yml
debug:
  active: true
  level: debug
```
You should be able to see some files in the `__pyfunceble_logging__` folder. 

Therefore, closing.

**Closed by funilrys** 2024-12-27 11:38 UTC
Labels: bug
