### ISSUE TITLE
BUG: idna conversion with --adblock

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#289] opened 2021-12-31 01:31 UTC
## Description
Was testing this zone https://github.com/dns-test/iploggerfilter/blob/master/filterlist with the adblocker enabled.

Related issues to this use case
- https://github.com/piperun/iploggerfilter/issues/49
- https://github.com/piperun/iploggerfilter/issues/50 Result files attached.

The issue:

In the INVALID Pyfunceble have converted `||yoütu.be^$important,all` to `xn--||yotu-6ya.be^$important,all`

## Configuration
https://mypdns.org/spirillen/PyFunceble/-/snippets/50

## Reproduction
1. pyfunceble -f https://github.com/dns-test/iploggerfilter/blob/master/filterlist --adblock
2. See the attachments in https://github.com/piperun/iploggerfilter/issues/50

## Expected behavior
No errors

## Versions

**OS:** Ubuntu focal

**Python Version:** 3.10

**PyFunceble Version:** pyfunceble 4.1.0b5.dev

## Additional context
Not for now

**Comment by spirillen** [comment] 2021-12-31 02:50
A side note to this

I'm starting to get a lot of these lines

![image](https://user-images.githubusercontent.com/44526987/147800208-021934cf-0fd8-48cf-8a22-3072bbece249.png)

**Comment by funilrys** [comment] 2021-12-31 17:45
Hey @spirillen,

I can't reproduce this ...

```bash
$  cat list.test 
||äxample.com^
||yoütu.be^$important,all
```

```bash
$ pyfunceble -f list.test --adblock --syntax --simple
xn--xample-9ta.com VALID
xn--yotu-1ra.be VALID


Status      Percentage   Amount      
----------- ------------ ------------
VALID       100%         2           
INVALID     0%           0           
```

Cheers!

**Comment by spirillen** [comment] 2021-12-31 19:17
Hmm couldn't reproduce my self on this device, only on the other one, but that one is busy testing https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Adult

Will get back when I've been able to rerun the test

**Comment by funilrys** [comment] 2022-01-29 10:16
Ping

**Comment by spirillen** [comment] 2022-01-30 04:49
Pong...

Saw them a few days ago, those `erllib3..`

Bit haven't seen the other issue since.

**Comment by funilrys** [comment] 2022-02-05 07:58
Closing. Feel free to reopen if necessary.

**Closed by funilrys** 2022-02-05 07:58 UTC
Labels: bug
